import PropTypes, { InferProps } from 'prop-types'
import styles from './styles.module.scss'
import Paper from '@mui/material/Paper'
import Link, { Url } from 'next/link'
import { useTranslation, i18n } from 'next-i18next'
import Head from 'next/head'
import { useRouter } from 'next/router'

export default function Header() {
  const router = useRouter()
  const { t } = useTranslation('common')

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Paper className={styles.header}>
          <Link href='/' locale={router.locale}>
            <a className={styles.logo}>
              <span className={styles.headline}>{t('header.headline')}</span>
              <span className={styles.bottomLine}>{t('header.bottom_line')}</span>
            </a>
          </Link>
          <Item href='youtube'>{t('header.links.videos')}</Item>
          <Item href='instagram'>{t('header.links.photos')}</Item>
          <Item href='twitter'>{t('header.links.tweets')}</Item>
          <Item href='github'>{t('header.links.repositories')}</Item>
        </Paper>
      </header>
    </>
  )  
}

Item.propTypes = {
  href: PropTypes.string,
  children: PropTypes.node
}
interface ItemProps {
  href: Url
  children: React.ReactNode
}
function Item(props: ItemProps) {
  const router = useRouter()

  return (
    <Link href={'/' + props.href} locale={router.locale}>
      <a className={styles.link}>{props.children}</a>
    </Link>
  )
}